### PR TITLE
Add finnish translations

### PR DESCRIPTION
**Pull request by lokalisoija**

### CODE REVIEW

**Comment by FoggyMtnDrifter** [comment]
Hey there! We just launched our new website and are now handling translations through [Crowdin](https://crowdin.com/project/rockylinuxorg). Please submit translations there, then when you have completed 100% of the translations, open an issue in this repository to notify us.

**Comment by lokalisoija** [comment]
Okay, Thanks for the info :)

**Comment by lokalisoija** [comment]
> Hey there! We just launched our new website and are now handling translations through [Crowdin](https://crowdin.com/project/rockylinuxorg). Please submit translations there, then when you have completed 100% of the translations, open an issue in this repository to notify us.

Done

**Comment by FoggyMtnDrifter** [comment]
> Done

Awesome! Please open an issue using the link below and provide the required info and I will get it added to the site: https://github.com/rocky-linux/rockylinux.org/issues/new?assignees=&labels=enhancement&template=translation_completed.md&title=Translation+Completed%3A+%3CINSERT+LANGUAGE+HERE%3E

**Pull request closed without merging**
