### PR TITLE
Translating the remaining strings and updating some of them

### PR DESCRIPTION
**Pull request by jordibalcellss**

### CODE REVIEW

**Comment by jordibalcellss** [comment]
Hi, a few days ago I proposed this merge request. It modifies the catalan (ca) translation, updating a few typos and adding remaining strings (like the one for sponsors). May I ask it to be considered? If you need any clarification about this translation, here I am. Looking forward to hearing from you! Cheers

**Comment by hbjydev** [comment]
Hi there! I'd be happy to accept this PR, but we just need someone to peer review it first who can read what you've written! :)

Rule #1 of translations; trust but verify :)

**Comment by hbjydev** [comment]
Also, can you rebase this onto the `develop` branch? Thanks! :D

**Comment by jordibalcellss** [comment]
Moving that towards develop

**Pull request closed without merging**
