### PR TITLE
Update community-update-december-2020.md

### PR DESCRIPTION
**Pull request by theAdmin10**
Updated broken wiki link

### CODE REVIEW

**Review by jorp — APPROVED** [review]
Thanks again for finding this. I've tweaked it to point to the Development team's page

**Comment by FoggyMtnDrifter** [comment]
It looks like Vercel successfully built a preview deployment for this PR, but it never reported the status back to GitHub. @hbjydev I'll let you deal with that. 😜

**Comment by hbjydev** [comment]
@ressonix Huh? Says checks are passing on my end, maybe it was just lagging behind?

**Comment by theAdmin10** [comment]
Updated broken link to point to development teams page.

**Comment by theAdmin10** [comment]
Updated this pull-request to the develop branch.

**Pull request merged**
