### PR TITLE
RC1 Release Update

### PR DESCRIPTION
**Pull request by hbjydev**
We're finally here! At RC1!

Check out the pages this brings with it (in the form of a post _and_ the /download page!)

### CODE REVIEW

**Comment by hbjydev** [comment]
@ressonix pre-commit pls

**Comment by FoggyMtnDrifter** [comment]
> @ressonix pre-commit pls

I just ran it, it passed all checks and didn't modify any files @hbjydev

**Comment by hbjydev** [comment]
Oh, I'm stupid, it was review needed, not pre-commit 😂

**Comment by hbjydev** [comment]
Can you approb me then plez?

**Review by FoggyMtnDrifter — APPROVED** [review]
Let's goooo!!!

**Pull request merged**
