### PR TITLE
New Site Release

### LINKED ISSUE #47: Partners page refinement
We're going to be including 280 character summaries for each partner (like we do the principal sponsors) to the partners page, can we refine the design so that the sponsors are offset each other with the character summaries listed beside each? See linked sketch for what this might look like...

https://web.tresorit.com/l/MfwMZ#YBusHX0SmOizBX2DtU0JbQ

I will create other issues to provide the wording for each partner

### LINKED ISSUE #48: Add 280c summary for Naver on Partners page
Here's the character summary for Naver:

> NAVER Cloud Platform is a South Korean cloud service that started in 2017 under NAVER Cloud, a subsidiary of NAVER. It provides over 170 individual services in 2021 and holds various security certifications including CSA STAR GOLD, GDPR, and more. It also currently provides cloud services in 10 locations around the world.

Please add this next to their logo on the Partners page

### LINKED ISSUE #63: Add 280c wording to AWS on Sponsor's page
Can we please add the following text next to the AWS logo?

> The RESF utilizes AWS to run much of the underlying infrastructure critical to the development and deployment of the services supporting Rocky Linux. From Koji builders for x86_64 and aarch64 running in EC2 to SRPM blob storage in S3, AWS is foundational to much of what we do. 

Thank you

### LINKED ISSUE #64: Add Fastly logo to Partners page
Fastly is an official partner so we want to make sure we add their logo. 

https://web.tresorit.com/l/zQdXn#KvnFrhdJUPlLY_Tv7ezTag

### PR DESCRIPTION
**Pull request by FoggyMtnDrifter**
closes #64 
closes #48 
closes #47 
closes #63

### CODE REVIEW

**Comment by hbjydev** [comment]
#### 📝Changed routes:


| [**/partners**](https://rockylinux-bqjs7f5xp-resforg.vercel.app/partners) | [**/sponsors**](https://rockylinux-bqjs7f5xp-resforg.vercel.app/sponsors) |
|:-:|:-:|
|<a href="https://rockylinux-bqjs7f5xp-resforg.vercel.app/partners">Screenshot of /partners</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/T8rhBxEG9BmP1zKkLrh3fSJzmYFLxmcQyeBE2TxLttWwXgh_Tx7gUtPlso_ImcN5H04uhqGU56uCpKBVk3BzBQ.png">(view full size)</a> |<a href="https://rockylinux-bqjs7f5xp-resforg.vercel.app/sponsors">Screenshot of /sponsors</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/XmuFuZBDmXIdpsUUs9Mm8CMevqRsXNNAPLXLIOqx_N0-6AgWKiCcrmNUDt0noNyWuiOs3XRwf5uRcIasXtIzsA.png">(view full size)</a> |







Commit 5ef4843fd6b099f20fde7ec0ebb65934da3a2356 (https://rockylinux-bqjs7f5xp-resforg.vercel.app).

**Comment by FoggyMtnDrifter** [comment]
@hbjydev Looks like I missed some font colors, I'll get those updated. Don't merge just yet.

**Comment by hbjydev** [comment]
@ressonix Can we get something specific to light theme too? That background doesn't seem to play well on light

**Comment by FoggyMtnDrifter** [comment]
@hbjydev The problem with light is that some of the logos use white in them, which doesn't play nicely with lighter colors. That's why I chose a lighter gray color. Do you have any other ideas for that? I'm open to them.

**Comment by FoggyMtnDrifter** [comment]
The gray color on the light theme is actually different from the dark version.

**Comment by hbjydev** [comment]
Ah, right... I guess we could see if there's any branding for lighter backgrounds? Like with NAVER Cloud for instance I'm sure we have a black logotype we can use somewhere.

If not, no worries, I'll push this through.

**Comment by FoggyMtnDrifter** [comment]
Yes, you're right. For some of the logos we do have dark variations, however, how are we to switch that based on the color scheme without using something like JavaScript? The only way I could get that to work is if we have SVG versions of each logo and use CSS magic like I did with the Rocky Linux logo.

**Comment by FoggyMtnDrifter** [comment]
Something I could do is just put a white background behind the logos if we have dark versions of all of them (like we do on 45Drives and OpenDrives logos) to make it consistent, that way we don't even have to worry about the color of the cards getting in the way of contrast.

I seriously need some sleep lol, I'm not thinking straight.

**Review by hbjydev — APPROVED** [review]

**Pull request merged**
